# Generated by Django 4.2.4 on 2023-08-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
    ]
