# Generated by Django 4.2.4 on 2023-08-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230819_2224'),
    ]

    operations = [
    ]
