# Generated by Django 4.2.4 on 2023-08-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230820_0650'),
    ]

    operations = [
    ]
