# Generated by Django 4.2.4 on 2023-08-20 09:08

from django.db import migrations, models

def set_publisher(apps, schema_editor):
    Book = apps.get_model('bookreviews', 'Book')
    for book in Book.objects.all():
        book.publisher = "Publisher"
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230820_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(set_publisher)
    ]
