# Generated by Django 4.2.4 on 2023-08-20 09:21

from django.db import migrations, models

def set_publisher(apps, schema_editor):
    Book = apps.get_model('reviews', 'Book')
    for book in Book.objects.all():
        book.publisher = "Publisher"
        book.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(default='2000-07-01'),
        ),
    ]
