# Generated by Django 4.2.4 on 2023-08-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.TextField(default='Reviewer', max_length=24),
        ),
    ]
