name: Django CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install Dependencies using Pipenv
      run: pipenv install --deploy --ignore-pipfile

    - name: Apply Migrations
      run: |
        pipenv run python manage.py makemigrations
        pipenv run python manage.py migrate

