name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: koffcheg
          POSTGRES_PASSWORD: 14881488
          POSTGRES_DB: bookreviewsdb
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv
      run: | 
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: pipenv install  --deploy --ignore-pipfile

    - name: Run migration check
      run: |
        chmod +x migrate.sh
        ./migrate.sh

    - name: Run migration
      run: |
        pipenv run python manage.py makemigrations
        pipenv run python manage.py migrate

    - name: Run tests
      run: pipenv run python manage.py test


